version: 2.1

jobs:
  install-deps:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_deps-{{ checksum "package.json" }}
      - run:
          command: npm i
      - save_cache:
          key: node_deps-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint-and-test:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: check code follow standard
          command: yarn check-all
      - run:
          name: tests
          command: yarn test

workflows:
  lint-and-test:
    jobs:
      - install-deps
      - lint-and-test:
          requires:
            - install-deps
