version: 2.1

jobs:
  install-deps:
    docker:
      - image: electronuserland/builder:14
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_deps-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: node_deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint-and-test:
    docker:
      - image: electronuserland/builder:14
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: check code follow standard
          command: yarn check-all
      - run:
          name: tests
          command: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build-ubuntu:
    docker:
      - image: electronuserland/builder:14
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: install dpkg and fakeroot
          command: |
            apt-get update -y
            apt-get install -y dpkg fakeroot
      - run:
          name: generate builds
          command: yarn make
      - store_artifacts:
          path: ~/project/out/make

workflows:
  lint-test-package:
    jobs:
      - install-deps
      - lint-and-test:
          requires:
            - install-deps
      - build-ubuntu:
          filters: &filters-build
            branches:
              only:
                - /release.*/
          requires:
            - lint-and-test
